[build-system]
requires = ["setuptools >= 42.0.0,<81", "wheel", "ansys_tools_protoc_helper>=0.4.0"]
build-backend = "setuptools.build_meta:__legacy__"

[project]
# Check https://flit.readthedocs.io/en/latest/pyproject_toml.html for all available sections
authors = [{name = "ANSYS, Inc.", email = "pyansys.core@ansys.com"}]
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Manufacturing",
  "Topic :: Scientific/Engineering",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
]
description = "The gRPC interface files for the Additive service."
license = {file = "LICENSE"}
maintainers = [{name = "ANSYS, Inc.", email = "pyansys.core@ansys.com"}]
name = "ansys-api-additive"
readme = "README.md"
requires-python = ">=3.10,<3.12"
dynamic = ["version"]
